-- =====================================================================
-- Smart Practical Batch & Timetable Generator - baseline schema
--
-- Written portably for H2 2.x (dev) and PostgreSQL 13+ (production):
--   * BIGINT GENERATED BY DEFAULT AS IDENTITY is standard SQL on both
--   * no vendor-specific types; VARCHAR is used instead of TEXT
--   * column names avoid H2/PostgreSQL reserved words (year, day, value, key)
--
-- Scheduling data is fully normalised. Multi-valued attributes such as
-- faculty preferred days/slots and lab availability live in their own
-- tables rather than JSON columns, so the solver can query them by index.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Organisation and identity
-- ---------------------------------------------------------------------
CREATE TABLE departments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(16)  NOT NULL,
    name            VARCHAR(128) NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_departments_code UNIQUE (code)
);

CREATE TABLE roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(32)  NOT NULL,
    description     VARCHAR(255),
    CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(64)  NOT NULL,
    email           VARCHAR(160) NOT NULL,
    password_hash   VARCHAR(120) NOT NULL,
    full_name       VARCHAR(128) NOT NULL,
    role_id         BIGINT       NOT NULL,
    department_id   BIGINT,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    last_login_at   TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_email    UNIQUE (email),
    CONSTRAINT fk_users_role     FOREIGN KEY (role_id)       REFERENCES roles (id),
    CONSTRAINT fk_users_dept     FOREIGN KEY (department_id) REFERENCES departments (id)
);
CREATE INDEX ix_users_role ON users (role_id);
CREATE INDEX ix_users_dept ON users (department_id);

-- ---------------------------------------------------------------------
-- Academic calendar
-- ---------------------------------------------------------------------
CREATE TABLE academic_terms (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_year   VARCHAR(16) NOT NULL,
    semester        INT         NOT NULL,
    start_date      DATE        NOT NULL,
    end_date        DATE        NOT NULL,
    is_current      BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_terms_year_sem UNIQUE (academic_year, semester),
    CONSTRAINT ck_terms_semester CHECK (semester BETWEEN 1 AND 12),
    CONSTRAINT ck_terms_dates    CHECK (end_date > start_date)
);

-- ---------------------------------------------------------------------
-- People
-- ---------------------------------------------------------------------
CREATE TABLE students (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT,
    roll_number     VARCHAR(32)  NOT NULL,
    name            VARCHAR(128) NOT NULL,
    email           VARCHAR(160) NOT NULL,
    department_id   BIGINT       NOT NULL,
    semester        INT          NOT NULL,
    study_year      INT          NOT NULL,
    division        VARCHAR(8)   NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_students_roll  UNIQUE (roll_number),
    CONSTRAINT uq_students_email UNIQUE (email),
    CONSTRAINT uq_students_user  UNIQUE (user_id),
    CONSTRAINT fk_students_user  FOREIGN KEY (user_id)       REFERENCES users (id),
    CONSTRAINT fk_students_dept  FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT ck_students_sem   CHECK (semester BETWEEN 1 AND 12),
    CONSTRAINT ck_students_year  CHECK (study_year BETWEEN 1 AND 6)
);
CREATE INDEX ix_students_dept_sem_div ON students (department_id, semester, division);
CREATE INDEX ix_students_status       ON students (status);

CREATE TABLE faculty (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT,
    employee_code     VARCHAR(32)  NOT NULL,
    name              VARCHAR(128) NOT NULL,
    email             VARCHAR(160) NOT NULL,
    department_id     BIGINT       NOT NULL,
    designation       VARCHAR(64)  NOT NULL,
    max_weekly_hours  INT          NOT NULL DEFAULT 18,
    status            VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_faculty_code  UNIQUE (employee_code),
    CONSTRAINT uq_faculty_email UNIQUE (email),
    CONSTRAINT uq_faculty_user  UNIQUE (user_id),
    CONSTRAINT fk_faculty_user  FOREIGN KEY (user_id)       REFERENCES users (id),
    CONSTRAINT fk_faculty_dept  FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT ck_faculty_hours CHECK (max_weekly_hours > 0)
);
CREATE INDEX ix_faculty_dept   ON faculty (department_id);
CREATE INDEX ix_faculty_status ON faculty (status);

-- ---------------------------------------------------------------------
-- Curriculum and physical resources
-- ---------------------------------------------------------------------
CREATE TABLE subjects (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_code          VARCHAR(32)  NOT NULL,
    subject_name          VARCHAR(160) NOT NULL,
    department_id         BIGINT       NOT NULL,
    semester              INT          NOT NULL,
    subject_type          VARCHAR(16)  NOT NULL DEFAULT 'PRACTICAL',
    practical_duration_min INT         NOT NULL DEFAULT 120,
    sessions_per_week     INT          NOT NULL DEFAULT 1,
    students_per_batch    INT          NOT NULL DEFAULT 30,
    required_lab_type     VARCHAR(48)  NOT NULL,
    status                VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at            TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_subjects_code    UNIQUE (subject_code),
    CONSTRAINT fk_subjects_dept    FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT ck_subjects_dur     CHECK (practical_duration_min > 0),
    CONSTRAINT ck_subjects_sessions CHECK (sessions_per_week > 0),
    CONSTRAINT ck_subjects_batch   CHECK (students_per_batch > 0),
    CONSTRAINT ck_subjects_sem     CHECK (semester BETWEEN 1 AND 12)
);
CREATE INDEX ix_subjects_dept_sem ON subjects (department_id, semester);

-- Qualification matrix: a faculty may only be assigned subjects listed here.
CREATE TABLE faculty_subjects (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id   BIGINT      NOT NULL,
    subject_id   BIGINT      NOT NULL,
    proficiency  VARCHAR(16) NOT NULL DEFAULT 'PRIMARY',
    CONSTRAINT uq_fac_subj      UNIQUE (faculty_id, subject_id),
    CONSTRAINT fk_fac_subj_fac  FOREIGN KEY (faculty_id) REFERENCES faculty (id)  ON DELETE CASCADE,
    CONSTRAINT fk_fac_subj_subj FOREIGN KEY (subject_id) REFERENCES subjects (id) ON DELETE CASCADE
);
CREATE INDEX ix_fac_subj_subject ON faculty_subjects (subject_id);

CREATE TABLE laboratories (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_code       VARCHAR(32)  NOT NULL,
    lab_name       VARCHAR(128) NOT NULL,
    department_id  BIGINT       NOT NULL,
    capacity       INT          NOT NULL,
    lab_type       VARCHAR(48)  NOT NULL,
    location       VARCHAR(128),
    status         VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_labs_code     UNIQUE (lab_code),
    CONSTRAINT fk_labs_dept     FOREIGN KEY (department_id) REFERENCES departments (id),
    CONSTRAINT ck_labs_capacity CHECK (capacity > 0)
);
CREATE INDEX ix_labs_type_status ON laboratories (lab_type, status);

-- ---------------------------------------------------------------------
-- Working-hours configuration (never hard-coded in application code)
-- ---------------------------------------------------------------------
CREATE TABLE time_slots (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label       VARCHAR(32) NOT NULL,
    start_time  TIME        NOT NULL,
    end_time    TIME        NOT NULL,
    slot_order  INT         NOT NULL,
    slot_type   VARCHAR(16) NOT NULL DEFAULT 'TEACHING',
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_slots_order UNIQUE (slot_order),
    CONSTRAINT ck_slots_time  CHECK (end_time > start_time),
    CONSTRAINT ck_slots_type  CHECK (slot_type IN ('TEACHING','BREAK','LUNCH','RESTRICTED','SPECIAL'))
);

CREATE TABLE working_days (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week  VARCHAR(12) NOT NULL,
    active       BOOLEAN     NOT NULL DEFAULT TRUE,
    day_order    INT         NOT NULL,
    CONSTRAINT uq_working_days UNIQUE (day_of_week)
);

-- Availability doubles as preference: PREFERRED slots satisfy soft constraint S1,
-- UNAVAILABLE slots are hard constraints H5/H6.
CREATE TABLE faculty_availability (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id    BIGINT      NOT NULL,
    day_of_week   VARCHAR(12) NOT NULL,
    time_slot_id  BIGINT      NOT NULL,
    availability  VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
    note          VARCHAR(255),
    CONSTRAINT uq_fac_avail     UNIQUE (faculty_id, day_of_week, time_slot_id),
    CONSTRAINT fk_fac_avail_fac FOREIGN KEY (faculty_id)   REFERENCES faculty (id)    ON DELETE CASCADE,
    CONSTRAINT fk_fac_avail_ts  FOREIGN KEY (time_slot_id) REFERENCES time_slots (id) ON DELETE CASCADE,
    CONSTRAINT ck_fac_avail     CHECK (availability IN ('AVAILABLE','UNAVAILABLE','PREFERRED'))
);
CREATE INDEX ix_fac_avail_lookup ON faculty_availability (faculty_id, day_of_week);

CREATE TABLE lab_availability (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_id        BIGINT      NOT NULL,
    day_of_week   VARCHAR(12) NOT NULL,
    time_slot_id  BIGINT      NOT NULL,
    availability  VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE',
    note          VARCHAR(255),
    CONSTRAINT uq_lab_avail     UNIQUE (lab_id, day_of_week, time_slot_id),
    CONSTRAINT fk_lab_avail_lab FOREIGN KEY (lab_id)       REFERENCES laboratories (id) ON DELETE CASCADE,
    CONSTRAINT fk_lab_avail_ts  FOREIGN KEY (time_slot_id) REFERENCES time_slots (id)   ON DELETE CASCADE,
    CONSTRAINT ck_lab_avail     CHECK (availability IN ('AVAILABLE','UNAVAILABLE','PREFERRED'))
);
CREATE INDEX ix_lab_avail_lookup ON lab_availability (lab_id, day_of_week);

CREATE TABLE holidays (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date  DATE         NOT NULL,
    name          VARCHAR(128) NOT NULL,
    description   VARCHAR(512),
    department_id BIGINT,
    CONSTRAINT uq_holiday_date  UNIQUE (holiday_date, department_id),
    CONSTRAINT fk_holiday_dept  FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE
);
CREATE INDEX ix_holidays_date ON holidays (holiday_date);

CREATE TABLE faculty_leaves (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id        BIGINT      NOT NULL,
    start_date        DATE        NOT NULL,
    end_date          DATE        NOT NULL,
    leave_type        VARCHAR(32) NOT NULL DEFAULT 'CASUAL',
    reason            VARCHAR(512),
    status            VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    applied_at        TIMESTAMP WITH TIME ZONE   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_by       BIGINT,
    reviewed_at       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_leave_faculty  FOREIGN KEY (faculty_id)  REFERENCES faculty (id) ON DELETE CASCADE,
    CONSTRAINT fk_leave_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id),
    CONSTRAINT ck_leave_dates    CHECK (end_date >= start_date),
    CONSTRAINT ck_leave_status   CHECK (status IN ('PENDING','APPROVED','REJECTED','CANCELLED'))
);
CREATE INDEX ix_leaves_faculty_dates ON faculty_leaves (faculty_id, start_date, end_date);
CREATE INDEX ix_leaves_status        ON faculty_leaves (status);

-- ---------------------------------------------------------------------
-- Practical batches
-- ---------------------------------------------------------------------
CREATE TABLE student_batches (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_code        VARCHAR(48)  NOT NULL,
    batch_name        VARCHAR(64)  NOT NULL,
    department_id     BIGINT       NOT NULL,
    subject_id        BIGINT       NOT NULL,
    academic_term_id  BIGINT       NOT NULL,
    division          VARCHAR(8)   NOT NULL,
    semester          INT          NOT NULL,
    capacity          INT          NOT NULL,
    student_count     INT          NOT NULL DEFAULT 0,
    required_lab_type VARCHAR(48)  NOT NULL,
    status            VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_batch_code     UNIQUE (batch_code),
    CONSTRAINT fk_batch_dept     FOREIGN KEY (department_id)    REFERENCES departments (id),
    CONSTRAINT fk_batch_subject  FOREIGN KEY (subject_id)       REFERENCES subjects (id)       ON DELETE CASCADE,
    CONSTRAINT fk_batch_term     FOREIGN KEY (academic_term_id) REFERENCES academic_terms (id),
    CONSTRAINT ck_batch_capacity CHECK (capacity > 0)
);
CREATE INDEX ix_batches_subject_div ON student_batches (subject_id, division);
CREATE INDEX ix_batches_term        ON student_batches (academic_term_id);

CREATE TABLE batch_students (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id    BIGINT NOT NULL,
    student_id  BIGINT NOT NULL,
    CONSTRAINT uq_batch_student      UNIQUE (batch_id, student_id),
    CONSTRAINT fk_batch_student_b    FOREIGN KEY (batch_id)   REFERENCES student_batches (id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_student_s    FOREIGN KEY (student_id) REFERENCES students (id)        ON DELETE CASCADE
);
CREATE INDEX ix_batch_students_student ON batch_students (student_id);

-- A "practical" is one schedulable demand: batch x subject, N sessions per week.
CREATE TABLE practicals (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id         BIGINT      NOT NULL,
    batch_id           BIGINT      NOT NULL,
    academic_term_id   BIGINT      NOT NULL,
    preferred_faculty_id BIGINT,
    sessions_per_week  INT         NOT NULL DEFAULT 1,
    duration_min       INT         NOT NULL DEFAULT 120,
    status             VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at         TIMESTAMP WITH TIME ZONE   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_practical         UNIQUE (subject_id, batch_id, academic_term_id),
    CONSTRAINT fk_practical_subject FOREIGN KEY (subject_id)         REFERENCES subjects (id)        ON DELETE CASCADE,
    CONSTRAINT fk_practical_batch   FOREIGN KEY (batch_id)           REFERENCES student_batches (id) ON DELETE CASCADE,
    CONSTRAINT fk_practical_term    FOREIGN KEY (academic_term_id)   REFERENCES academic_terms (id),
    CONSTRAINT fk_practical_faculty FOREIGN KEY (preferred_faculty_id) REFERENCES faculty (id)
);

-- ---------------------------------------------------------------------
-- Timetables
-- ---------------------------------------------------------------------
CREATE TABLE timetables (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(128) NOT NULL,
    academic_term_id   BIGINT       NOT NULL,
    department_id      BIGINT,
    status             VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    score              DOUBLE PRECISION,
    hard_violations    INT          NOT NULL DEFAULT 0,
    soft_penalty       DOUBLE PRECISION,
    solver_status      VARCHAR(32),
    solver_engine      VARCHAR(48),
    solver_runtime_ms  BIGINT,
    generated_at       TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    generated_by       BIGINT,
    approved_at        TIMESTAMP WITH TIME ZONE,
    approved_by        BIGINT,
    published_at       TIMESTAMP WITH TIME ZONE,
    notes              VARCHAR(1024),
    CONSTRAINT fk_tt_term      FOREIGN KEY (academic_term_id) REFERENCES academic_terms (id),
    CONSTRAINT fk_tt_dept      FOREIGN KEY (department_id)    REFERENCES departments (id),
    CONSTRAINT fk_tt_generator FOREIGN KEY (generated_by)     REFERENCES users (id),
    CONSTRAINT fk_tt_approver  FOREIGN KEY (approved_by)      REFERENCES users (id),
    CONSTRAINT ck_tt_status    CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED','REJECTED'))
);
CREATE INDEX ix_timetables_status ON timetables (status, academic_term_id);

CREATE TABLE timetable_entries (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timetable_id      BIGINT      NOT NULL,
    practical_id      BIGINT,
    batch_id          BIGINT      NOT NULL,
    subject_id        BIGINT      NOT NULL,
    faculty_id        BIGINT      NOT NULL,
    lab_id            BIGINT      NOT NULL,
    day_of_week       VARCHAR(12) NOT NULL,
    start_time_slot_id BIGINT     NOT NULL,
    end_time_slot_id  BIGINT      NOT NULL,
    start_time        TIME        NOT NULL,
    end_time          TIME        NOT NULL,
    session_index     INT         NOT NULL DEFAULT 1,
    status            VARCHAR(16) NOT NULL DEFAULT 'SCHEDULED',
    created_at        TIMESTAMP WITH TIME ZONE   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tte_timetable FOREIGN KEY (timetable_id)       REFERENCES timetables (id)      ON DELETE CASCADE,
    CONSTRAINT fk_tte_practical FOREIGN KEY (practical_id)       REFERENCES practicals (id)      ON DELETE SET NULL,
    CONSTRAINT fk_tte_batch     FOREIGN KEY (batch_id)           REFERENCES student_batches (id),
    CONSTRAINT fk_tte_subject   FOREIGN KEY (subject_id)         REFERENCES subjects (id),
    CONSTRAINT fk_tte_faculty   FOREIGN KEY (faculty_id)         REFERENCES faculty (id),
    CONSTRAINT fk_tte_lab       FOREIGN KEY (lab_id)             REFERENCES laboratories (id),
    CONSTRAINT fk_tte_start_ts  FOREIGN KEY (start_time_slot_id) REFERENCES time_slots (id),
    CONSTRAINT fk_tte_end_ts    FOREIGN KEY (end_time_slot_id)   REFERENCES time_slots (id),
    CONSTRAINT ck_tte_time      CHECK (end_time > start_time),
    CONSTRAINT ck_tte_status    CHECK (status IN ('SCHEDULED','RESCHEDULED','CANCELLED'))
);
-- Indexes backing the conflict detector's overlap queries.
CREATE INDEX ix_tte_timetable_day ON timetable_entries (timetable_id, day_of_week);
CREATE INDEX ix_tte_faculty_slot  ON timetable_entries (timetable_id, faculty_id, day_of_week);
CREATE INDEX ix_tte_lab_slot      ON timetable_entries (timetable_id, lab_id, day_of_week);
CREATE INDEX ix_tte_batch_slot    ON timetable_entries (timetable_id, batch_id, day_of_week);

-- ---------------------------------------------------------------------
-- Conflicts, rescheduling, notifications, audit
-- ---------------------------------------------------------------------
CREATE TABLE conflicts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timetable_id        BIGINT,
    conflict_type       VARCHAR(40)  NOT NULL,
    severity            VARCHAR(16)  NOT NULL,
    description         VARCHAR(1024) NOT NULL,
    suggested_resolution VARCHAR(1024),
    faculty_id          BIGINT,
    batch_id            BIGINT,
    lab_id              BIGINT,
    subject_id          BIGINT,
    entry_id            BIGINT,
    other_entry_id      BIGINT,
    day_of_week         VARCHAR(12),
    conflict_date       DATE,
    start_time          TIME,
    end_time            TIME,
    status              VARCHAR(16)  NOT NULL DEFAULT 'OPEN',
    detected_at         TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_conf_timetable FOREIGN KEY (timetable_id) REFERENCES timetables (id)      ON DELETE CASCADE,
    CONSTRAINT fk_conf_faculty   FOREIGN KEY (faculty_id)   REFERENCES faculty (id),
    CONSTRAINT fk_conf_batch     FOREIGN KEY (batch_id)     REFERENCES student_batches (id),
    CONSTRAINT fk_conf_lab       FOREIGN KEY (lab_id)       REFERENCES laboratories (id),
    CONSTRAINT fk_conf_subject   FOREIGN KEY (subject_id)   REFERENCES subjects (id),
    CONSTRAINT ck_conf_severity  CHECK (severity IN ('CRITICAL','HIGH','MEDIUM','LOW')),
    CONSTRAINT ck_conf_status    CHECK (status IN ('OPEN','RESOLVED','IGNORED'))
);
CREATE INDEX ix_conflicts_status ON conflicts (status, severity);
CREATE INDEX ix_conflicts_tt     ON conflicts (timetable_id);

CREATE TABLE reschedules (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timetable_entry_id  BIGINT       NOT NULL,
    timetable_id        BIGINT       NOT NULL,
    reason              VARCHAR(40)  NOT NULL,
    reason_detail       VARCHAR(512),
    affected_date       DATE,
    original_day        VARCHAR(12)  NOT NULL,
    original_start      TIME         NOT NULL,
    original_end        TIME         NOT NULL,
    original_faculty_id BIGINT       NOT NULL,
    original_lab_id     BIGINT       NOT NULL,
    new_day             VARCHAR(12),
    new_start           TIME,
    new_end             TIME,
    new_faculty_id      BIGINT,
    new_lab_id          BIGINT,
    candidate_score     DOUBLE PRECISION,
    status              VARCHAR(16)  NOT NULL DEFAULT 'PROPOSED',
    initiated_by        BIGINT,
    approved_by         BIGINT,
    created_at          TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at         TIMESTAMP WITH TIME ZONE,
    applied_at          TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_resch_entry     FOREIGN KEY (timetable_entry_id)  REFERENCES timetable_entries (id) ON DELETE CASCADE,
    CONSTRAINT fk_resch_timetable FOREIGN KEY (timetable_id)        REFERENCES timetables (id)        ON DELETE CASCADE,
    CONSTRAINT fk_resch_of        FOREIGN KEY (original_faculty_id) REFERENCES faculty (id),
    CONSTRAINT fk_resch_ol        FOREIGN KEY (original_lab_id)     REFERENCES laboratories (id),
    CONSTRAINT fk_resch_nf        FOREIGN KEY (new_faculty_id)      REFERENCES faculty (id),
    CONSTRAINT fk_resch_nl        FOREIGN KEY (new_lab_id)          REFERENCES laboratories (id),
    CONSTRAINT fk_resch_init      FOREIGN KEY (initiated_by)        REFERENCES users (id),
    CONSTRAINT fk_resch_appr      FOREIGN KEY (approved_by)         REFERENCES users (id),
    CONSTRAINT ck_resch_status    CHECK (status IN ('PROPOSED','APPROVED','REJECTED','APPLIED','CANCELLED'))
);
CREATE INDEX ix_resch_status ON reschedules (status);
CREATE INDEX ix_resch_entry  ON reschedules (timetable_entry_id);

-- Ranked alternatives surfaced to the coordinator for a reschedule request.
CREATE TABLE reschedule_candidates (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reschedule_id      BIGINT      NOT NULL,
    rank_order         INT         NOT NULL,
    day_of_week        VARCHAR(12) NOT NULL,
    start_time_slot_id BIGINT      NOT NULL,
    end_time_slot_id   BIGINT      NOT NULL,
    start_time         TIME        NOT NULL,
    end_time           TIME        NOT NULL,
    faculty_id         BIGINT      NOT NULL,
    lab_id             BIGINT      NOT NULL,
    score              DOUBLE PRECISION NOT NULL,
    score_breakdown    VARCHAR(1024),
    selected           BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_rc_resch   FOREIGN KEY (reschedule_id)      REFERENCES reschedules (id)  ON DELETE CASCADE,
    CONSTRAINT fk_rc_faculty FOREIGN KEY (faculty_id)         REFERENCES faculty (id),
    CONSTRAINT fk_rc_lab     FOREIGN KEY (lab_id)             REFERENCES laboratories (id),
    CONSTRAINT fk_rc_sts     FOREIGN KEY (start_time_slot_id) REFERENCES time_slots (id),
    CONSTRAINT fk_rc_ets     FOREIGN KEY (end_time_slot_id)   REFERENCES time_slots (id)
);
CREATE INDEX ix_rc_resch ON reschedule_candidates (reschedule_id, rank_order);

CREATE TABLE notifications (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT       NOT NULL,
    title               VARCHAR(160) NOT NULL,
    body                VARCHAR(1024) NOT NULL,
    category            VARCHAR(32)  NOT NULL DEFAULT 'GENERAL',
    severity            VARCHAR(16)  NOT NULL DEFAULT 'INFO',
    related_entity_type VARCHAR(48),
    related_entity_id   BIGINT,
    read_at             TIMESTAMP WITH TIME ZONE,
    created_at          TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_notif_user_unread ON notifications (user_id, read_at);

CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    username    VARCHAR(64),
    action      VARCHAR(64)  NOT NULL,
    entity_type VARCHAR(64)  NOT NULL,
    entity_id   BIGINT,
    old_value   VARCHAR(2048),
    new_value   VARCHAR(2048),
    ip_address  VARCHAR(64),
    user_agent  VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX ix_audit_entity  ON audit_logs (entity_type, entity_id);
CREATE INDEX ix_audit_created ON audit_logs (created_at);

-- ---------------------------------------------------------------------
-- Tunable optimisation weights (spec section 16). Stored as rows so an
-- administrator can retune the objective without a redeploy.
-- ---------------------------------------------------------------------
CREATE TABLE optimization_weights (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weight_key  VARCHAR(64)      NOT NULL,
    weight_value DOUBLE PRECISION NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uq_weight_key UNIQUE (weight_key)
);
