-- =====================================================================
-- Fixed commitments: recurring weekly obligations the practical optimiser
-- must schedule around but may not move - fixed lectures, meetings, or
-- externally reserved laboratory slots (spec sections 8 and 11).
--
-- A commitment blocks the covered (day, period) cells for its faculty member
-- and/or laboratory, and its duration is added to that faculty member's total
-- weekly workload, so reports and the balancing objective reflect
-- "fixed lecture + practical", not practical hours alone.
-- =====================================================================
CREATE TABLE fixed_commitments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title               VARCHAR(128) NOT NULL,
    commitment_type     VARCHAR(24)  NOT NULL DEFAULT 'LECTURE',
    faculty_id          BIGINT,
    lab_id              BIGINT,
    department_id       BIGINT,
    academic_term_id    BIGINT,
    day_of_week         VARCHAR(12)  NOT NULL,
    start_time_slot_id  BIGINT       NOT NULL,
    end_time_slot_id    BIGINT       NOT NULL,
    note                VARCHAR(255),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fc_faculty  FOREIGN KEY (faculty_id)         REFERENCES faculty (id)         ON DELETE CASCADE,
    CONSTRAINT fk_fc_lab      FOREIGN KEY (lab_id)             REFERENCES laboratories (id)    ON DELETE CASCADE,
    CONSTRAINT fk_fc_dept     FOREIGN KEY (department_id)      REFERENCES departments (id)     ON DELETE CASCADE,
    CONSTRAINT fk_fc_term     FOREIGN KEY (academic_term_id)   REFERENCES academic_terms (id)  ON DELETE CASCADE,
    CONSTRAINT fk_fc_start_ts FOREIGN KEY (start_time_slot_id) REFERENCES time_slots (id),
    CONSTRAINT fk_fc_end_ts   FOREIGN KEY (end_time_slot_id)   REFERENCES time_slots (id),
    -- A commitment with neither a faculty member nor a lab would block nothing.
    CONSTRAINT ck_fc_target   CHECK (faculty_id IS NOT NULL OR lab_id IS NOT NULL)
);
CREATE INDEX ix_fc_faculty ON fixed_commitments (faculty_id);
CREATE INDEX ix_fc_lab     ON fixed_commitments (lab_id);
CREATE INDEX ix_fc_term    ON fixed_commitments (academic_term_id);
